import "@/app/globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import AppTopbar from "@/components/app-topbar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <AppTopbar />
              <div className="grid-box flex-1 overflow-y-hidden grid gap-3 items-center justify-items-center font-[family-name:var(--font-geist-sans)] bg-neutral-50">
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
        </body>
      </Providers>
    </html>
  );
}
